---
- name: talk to all hosts just so we can learn about them
  hosts: all
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}
    - name: Display variables/facts known for a host
      debug:
        msg: System {{ inventory_hostname }} has OS {{ ansible_facts['distribution'] }} version {{ ansible_facts['distribution_version'] }}

# now just on the CentOS hosts...
- hosts: os_CentOS
  gather_facts: False
  tasks:
   - name: Executing shell command
     shell: id
# or the other once...
- hosts: os_Debian
  gather_facts: False
  tasks:
   - name: Executing shell command
     shell: id
